[package]
name = "tappd-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
prpc = "0.2.1"
prost = "0.12.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1"
scale = { version = "3.6.12", package = "parity-scale-codec", features = ["derive"] }

[build-dependencies]
prpc-build = "0.2.1"
